base_url: http://192.168.13.141:40010
browser:
  headless: false
  slow_mo: 0
  timeout: 30000
innorelease:
  password: zxcvb1234
  url: http://192.168.13.55:8090
  username: admin
product_name: RansomCruncher
qa_server_url: http://192.168.13.55:8080
selectors:
  login:
    password_input: input#password
    submit_button: input#loginBtn
    username_input: input#memberId
